name: Deploy Backend to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: SAM Build
        run: sam build -t template-python.yaml

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name serverless-chat-backend \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              ConnectionsTableName=ChatConnections \
              MessagesTableName=ChatMessages \
              UploadBucketName=chat-file-uploads-cpsc465

      - name: Get WebSocket URL
        run: |
          aws cloudformation describe-stacks \
            --stack-name serverless-chat-backend \
            --query 'Stacks[0].Outputs[?OutputKey==`WebSocketURI`].OutputValue' \
            --output text \
            --region us-east-1
